# Specify a base image.
FROM node:12-alpine AS alpine

# Project working directory.
WORKDIR /data-archive-frontend

# Copy the contents of the project to the image
COPY . .

# Run 'yarn build' when the container starts.
CMD ["yarn", "build"]